-- =============================================================================
-- MIGRATION 024: Invoice Slip Settings & Records
-- =============================================================================
-- Adds:
-- 1. invoice_settings - Organization-level invoice customization
-- 2. invoice_records - Track generated invoices with serial numbers
-- =============================================================================

-- =============================================================================
-- 1) Invoice Settings Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.invoice_settings (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  
  -- Header
  business_name TEXT NOT NULL DEFAULT '',
  tagline TEXT DEFAULT '',
  slogan TEXT DEFAULT '',
  logo_url TEXT DEFAULT '',
  
  -- Business Details
  ntn_number TEXT DEFAULT '',
  ceo_name TEXT DEFAULT '',
  phone_numbers TEXT[] DEFAULT '{}',
  business_address TEXT DEFAULT '',
  
  -- Styling
  primary_color TEXT DEFAULT '#DC2626',
  
  -- Section Visibility
  show_seller_photo BOOLEAN DEFAULT true,
  show_buyer_photo BOOLEAN DEFAULT true,
  show_vehicle_photo BOOLEAN DEFAULT true,
  show_accessories_section BOOLEAN DEFAULT true,
  show_documents_section BOOLEAN DEFAULT true,
  show_witness_section BOOLEAN DEFAULT true,
  show_notes_section BOOLEAN DEFAULT true,
  show_extra_requirements BOOLEAN DEFAULT true,
  show_profession_field BOOLEAN DEFAULT true,
  show_swdo_field BOOLEAN DEFAULT true,
  
  -- Default Text
  default_note_text TEXT DEFAULT 'Note: Seller is liable to clear all documents, token taxes and all liabilities before handing over the vehicle before this day seller is responsible for the use the above mentioned vehicle, any FIR, token taxes, liabilities challan etc.
Both parties (Seller and buyer) have agreed the sale in their clear consciousness, if any of the party steps back from the deal then showroom is not responsible. Both parties are liable to pay the commission of the showroom. This receipt is written and signed by both parties for the record.
Buyer is required to transfer the Vehicle in his Name and complete 15 Police Verification within fifteen days of receiving the vehicle. After 15 days, the showroom will not be responsible.',
  default_extra_requirements TEXT DEFAULT 'Vehicle and documents, along with the original slip and number plates, have been handed over to the client.',
  
  -- Serial Number Config
  invoice_prefix TEXT DEFAULT '',
  next_serial_number INTEGER DEFAULT 1,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  
  CONSTRAINT invoice_settings_org_unique UNIQUE (organization_id)
);

-- =============================================================================
-- 2) Invoice Records Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.invoice_records (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  
  -- Invoice Details
  invoice_type TEXT NOT NULL CHECK (invoice_type IN ('sale', 'exchange', 'japan_import')),
  entity_id UUID NOT NULL,
  serial_number INTEGER NOT NULL,
  invoice_number TEXT NOT NULL,
  
  -- Generated By
  generated_by UUID REFERENCES public.profiles(id),
  generated_at TIMESTAMPTZ DEFAULT now(),
  
  -- Metadata
  metadata JSONB DEFAULT '{}',
  
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_invoice_records_org ON public.invoice_records(organization_id);
CREATE INDEX IF NOT EXISTS idx_invoice_records_entity ON public.invoice_records(entity_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_invoice_records_org_serial ON public.invoice_records(organization_id, serial_number);

-- =============================================================================
-- 3) Updated At Triggers
-- =============================================================================
CREATE TRIGGER set_invoice_settings_updated_at
  BEFORE UPDATE ON public.invoice_settings
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

-- =============================================================================
-- 4) RLS Policies
-- =============================================================================
ALTER TABLE public.invoice_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_records ENABLE ROW LEVEL SECURITY;

-- Invoice Settings: org members can read
CREATE POLICY "Users can view own org invoice settings"
  ON public.invoice_settings FOR SELECT TO authenticated
  USING (organization_id = public.get_auth_org_id());

-- Invoice Settings: admin/manager can insert
CREATE POLICY "Admins can insert invoice settings"
  ON public.invoice_settings FOR INSERT TO authenticated
  WITH CHECK (organization_id = public.get_auth_org_id());

-- Invoice Settings: admin/manager can update
CREATE POLICY "Admins can update invoice settings"
  ON public.invoice_settings FOR UPDATE TO authenticated
  USING (organization_id = public.get_auth_org_id())
  WITH CHECK (organization_id = public.get_auth_org_id());

-- Invoice Records: org members can read
CREATE POLICY "Users can view own org invoice records"
  ON public.invoice_records FOR SELECT TO authenticated
  USING (organization_id = public.get_auth_org_id());

-- Invoice Records: authenticated can insert
CREATE POLICY "Users can create invoice records"
  ON public.invoice_records FOR INSERT TO authenticated
  WITH CHECK (organization_id = public.get_auth_org_id());

-- Service role full access
CREATE POLICY "Service role full access invoice_settings"
  ON public.invoice_settings FOR ALL TO service_role
  USING (true) WITH CHECK (true);

CREATE POLICY "Service role full access invoice_records"
  ON public.invoice_records FOR ALL TO service_role
  USING (true) WITH CHECK (true);

-- =============================================================================
-- 5) Function to get next invoice number atomically
-- =============================================================================
CREATE OR REPLACE FUNCTION public.get_next_invoice_number(p_org_id UUID, p_invoice_type TEXT, p_entity_id UUID)
RETURNS TABLE(serial_num INTEGER, invoice_num TEXT) AS $$
DECLARE
  v_prefix TEXT;
  v_serial INTEGER;
  v_invoice_num TEXT;
BEGIN
  -- Get or create settings
  INSERT INTO public.invoice_settings (organization_id)
  VALUES (p_org_id)
  ON CONFLICT (organization_id) DO NOTHING;
  
  -- Atomically increment and get
  UPDATE public.invoice_settings
  SET next_serial_number = next_serial_number + 1
  WHERE organization_id = p_org_id
  RETURNING next_serial_number - 1, invoice_prefix
  INTO v_serial, v_prefix;
  
  -- Build invoice number
  IF v_prefix IS NOT NULL AND v_prefix != '' THEN
    v_invoice_num := v_prefix || '-' || LPAD(v_serial::TEXT, 4, '0');
  ELSE
    v_invoice_num := LPAD(v_serial::TEXT, 4, '0');
  END IF;
  
  -- Record the invoice
  INSERT INTO public.invoice_records (organization_id, invoice_type, entity_id, serial_number, invoice_number)
  VALUES (p_org_id, p_invoice_type, p_entity_id, v_serial, v_invoice_num);
  
  RETURN QUERY SELECT v_serial, v_invoice_num;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';
